### ISSUE TITLE
info about recipes for MPM package building

### ISSUE THREAD

**Issue by redblade** [mikelangelo-project/capstan-packages#17]
Hi,
so far, a good use case I see for Mikelangelo is the development in Java/Python/NodeJS with your precompiled packages but I am exploring the [recipe part](https://github.com/mikelangelo-project/capstan-packages) for a EU project.

I need a clarification about the workflow to create new MPM packages.
According to [this post](https://www.mikelangelo-project.eu/2017/08/the-art-of-preparing-osv-packages/), I have to use a [Docker image](https://hub.docker.com/r/mikelangelo/capstan-packages/) for the building and, from [this picture](https://www.mikelangelo-project.eu/wp-content/uploads/2017/08/building-phase-running-phase.png), it seems I can install the apt packages I need (BTW, go/capstan is ok, but why Java is needed in this phase?)

1st question is if about these apt packages: they will not be available in the final package and they are mentioned only to support the building, right?

2nd: if I needed an unikernel image with iptables, I should refer to the [OSv apps examples](https://github.com/cloudius-systems/osv-apps) and download the .so or build them from source, just like the Python examples [here](https://github.com/cloudius-systems/osv-apps/tree/master/python27) and [here](https://github.com/cloudius-systems/osv-apps/tree/master/python27-fromsource), correct? Basically, I cannot simply do an apt-get install iptables but I have to manage the dependencies, get the related .so and prepare the recipe for that, right?

3rd: from the statement "Preparing a package requires knowledge about the application itself as well as the OSv limitations" I should be also aware of the limitations of the application I am going to build (I guess for example no usage of fork(), exec(), etc.). Where could I found more details on these limitations? Just to understand if and how an existing app could be ported on unikernel,  although I see there are [many interesting examples](https://github.com/cloudius-systems/osv-apps/blob/master/mysql) available.

Thanks in advance for the help provided. 

BR
Francesco

**Comment by miha-plesko** [comment]
Hi @redblade ,

0) Why Java is needed in this phase? -> so in this phase we install everything we will ever need to compile any package. We happen tp need Java to compile some packages (apache.spark I think) so we install it here.

1) True. The "building phase" could be better named as "prepare building environment in docker container". It creates no MPM package yet. MPM packages are only created in "running phase" where each recipe copies files it wants into the resulting MPM package; no black magic here in building phase.

2) True. It doesn't really matter what are you `apt install`-ing into Docker container, only the files that you specifically copy into the result directory (per recipe) will be gzipped into MPM package. If you want a new MPM package with iptables, then you need to write a recipe for it, yes. Please see [here](https://github.com/mikelangelo-project/capstan-packages/blob/master/doc/recipes.md) for instructions. In case osv-apps repo already contains iptables app, then you can make use of it like we do for Erlang for example ([recipe](https://github.com/mikelangelo-project/capstan-packages/blob/master/docker_files/recipes/erlang-7.0/build.sh#L17)). If osv-apps doesn't have such iptables yet, then your recipe will have to do it from scratch (see [python recipe](https://github.com/mikelangelo-project/capstan-packages/blob/master/docker_files/recipes/python-2.7/build.sh), for example).

3) Huh, good question, I'm not sure there is some list of things to be careful about. Not using `fork` is the most obvious one, yes. Perhaps you could read [this article](https://www.usenix.org/system/files/conference/atc14/atc14-paper-kivity.pdf) to understand better what OSv is all about. I suggest you ask this on the OSv repository: https://github.com/cloudius-systems/osv

**Comment by justinc1** [comment]
@redblade
>  image with iptables

The iptables command is only a userspace management tool for Linux iptables/nftables. The real work is then done in Linux kernel (the iptable_nat,iptable_mangle etc moduels). If you are thinking about OSv and iptables-based firewall, than that (kernel) part will be missing in OSv. Getting the /usr/sbin/iptables (/usr/sbin/xtables-multi) compiled will not be enough.

**Comment by redblade** [comment]
Interesting, maybe another thing to ask about the limitation of OSv
